[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.28.0",
    "gradio-client>=1.10.0",
    "numpy>=2.2.5",
]
